language: csharp
solution: "./OnlineLibrary.sln"
script: 
  - xbuild /p:Configuration=Release ./OnlineLibrary.sln
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  on:
    branch: master
notifications:
  email: false
