language: csharp
solution: "./OnlineBookLibrary.sln"
script: 
  - xbuild /p:Configuration=Release ./OnlineBookLibrary.sln
deploy:
  provider: azure_web_apps
  verbose: true
notifications:
  email: false
